### ISSUE TITLE
NameError: name 'img_id' is not defined

### ISSUE THREAD

**Issue by netrunner-exe** [a312863063/SimSwap-train#20]
```
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 72, in <module>
    no_simswaplogo=opt.no_simswaplogo,use_mask=opt.use_mask, name=opt.name)
  File "/content/SimSwap-train/util/videoswap.py", line 82, in video_swap
    swap_result = swap_model(img_id, input_norm, id_vetor, None)[0]
NameError: name 'img_id' is not defined
```

**Comment by a312863063** [comment]
Hi, I'm sorry I uploaded a wrong version. I fixed it and update the Readme.md. Thank you!
