### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x131072 and 25088x512)

### ISSUE THREAD

**Issue by netrunner-exe** [a312863063/SimSwap-train#21]
When i use `python test_video_swapsingle.py --image_size 512` it show an error:
```
load pretrained model:./checkpoints/CelebA_512_finetune/latest_net_G.pth
input mean and std: 127.5 127.5
find model: ./insightface_func/models/antelope/glintr100.onnx recognition
find model: ./insightface_func/models/antelope/scrfd_10g_bnkps.onnx detection
set det-size: (640, 640)
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 68, in <module>
    latend_id = model.netArc(img_id_downsample)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/SimSwap-train/models/models.py", line 145, in forward
    x = self.fc(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x131072 and 25088x512)
```
If change 512 to 244 all works

**Comment by a312863063** [comment]
Fixed. There are many test files, we need to modify scale_factor=0.5 to scale_factor=112/crop_size in each file.
